---
- hosts: manager,controller,edge
  gather_facts: no
  vars_files: 
    - ./var.yml 
  tasks:

    - name: check ntp server configuration 
      raw: get ntp-server
      register: ntp
      changed_when: false
     
    - name: check log server configuration
      raw: get logging-servers
      register: log
      changed_when: false

    - name: configure ntp server 
      raw: set ntp-server {{ misc.ntp }}
      when: ntp.stdout_lines[0] is undefined or ntp.stdout_lines[0] !=  "{{ misc.ntp }}"

    - name: configure log server 
      raw: set logging-server {{ misc.log }}:514 proto udp level warning
      when: log.stdout_lines[0] is undefined or "{{ misc.log }}" not in log.stdout_lines[0] 

- hosts: host
  gather_facts: no
  vars_files:
    - ./var.yml
  tasks:
   
    - name: disable ipv6 
      command: esxcli network ip set --ipv6-enabled=false

    - name: check ntp configuration in host 
      command: cat /etc/ntp.conf
      register: ntp
      changed_when: false
      tags:
        - host

    - lineinfile:
        path: /etc/ntp.conf
        line: server {{ misc.ntp }}
        create: yes
      when: '"{{ misc.ntp }}" not in ntp'
      tags:
        - host

    - name: check ntpd service 
      command: /etc/init.d/ntpd status
      ignore_errors: yes
      register: svc1
      changed_when: false
      tags:
        - host 

    - name: check ntpq -p 
      command: ntpq -p 
      register: svc2
      changed_when: false
      tags:
        - host

    - name: start ntp service 
      command: /etc/init.d/ntpd restart
      when: '"ntpd is running" not in svc1.stdout or "INIT" in svc2.stdout'
      tags: 
        - host    
