
---
- hosts: manager,controller,edge
  gather_facts: no
  vars_files:
    - ./var.yml
  tasks:

    - name: check ntp server configuration
      raw: get ntp-server
      register: ntp

    - name: check log server configuration
      raw: get logging-servers | find {{misc.log}}
      register: log
      tags:
        - log

    - debug:
        var: log
      tags:
        - log

    - name: configure ntp server
      raw: set ntp-server {{ misc.ntp }}
      when: ntp.stdout_lines[0] is undefined or ntp.stdout_lines[0] !=  "{{ misc.ntp }}"

    - name: configure log server
      raw: set logging-server {{ misc.log }}:514 proto udp level warning
      when: log.stdout_lines == []
      tags:
        - log

- hosts: host
  gather_facts: no
  vars_files:
    - ./var.yml
  tasks:

    - name: check ntp configuration in host
      command: cat /etc/ntp.conf
      register: ntp
      tags:
        - host

    - lineinfile:
        path: /etc/ntp.conf
        line: server {{ misc.ntp }}
        create: yes
      when: '"{{ misc.ntp }}" not in ntp'
      tags:
        - host

    - name: check ntpd service
      command: /etc/init.d/ntpd status
      ignore_errors: yes
      register: svc1
      tags:
        - host

    - name: check ntpq -p
      command: ntpq -p
      register: svc2
      tags:
        - host

    - name: start ntp service
      command: /etc/init.d/ntpd restart
      when: '"ntpd is running" not in svc1.stdout or "INIT" in svc2.stdout'
      tags:
        - host
