---
- hosts: manager,controller,edge
  gather_facts: no
  vars_files: 
    - ./var.yml 
  tasks:

    - name: check ntp server configuration 
      raw: get ntp-server
      register: ntp

    - debug:
        var: ntp.stdout_lines[0]
     
    - name: check log server configuration
      raw: get logging-servers
      register: log

    - debug:
        var: log.stdout_lines[0]

    - name: configure ntp server 
      raw: set ntp-server {{ misc.ntp }}
      when: ntp.stdout_lines[0] is undefined or ntp.stdout_lines[0] !=  "{{ misc.ntp }}"

    - name: configure log server 
      raw: set logging-server {{ misc.log }}:514 proto udp level warning
      when: log.stdout_lines[0] is undefined or "{{ misc.log }}" not in log.stdout_lines[0] 

