---
- hosts: manager
  gather_facts: no
  vars_files:
    - ./var.yml

  tasks:
# check nsx manager
    - name: check management cluster status on manager
      raw: get management-cluster status
      register: mgr
      failed_when: "'STABLE' not in mgr.stdout_lines[3]"

    - name: check controller cluster status on manager
      raw: get management-cluster status
      register: mgr
      failed_when: "'STABLE' not in mgr.stdout_lines[10]"

#    - debug:
#        var: mgr.stdout_lines[10]

# check nsx controller 
- hosts: controller
  gather_facts: no
  tasks:
    - name: check manager connecting on controller
      raw: get managers
      register: getmgr
      failed_when: "'Connected' not in getmgr.stdout_lines[0]"

#    - debug:
#        var: getmgr.stdout_lines

    - name: check controller cluster status on controller nodes
      raw: get control-cluster status
      register: cluster
      failed_when: "'true' not in cluster.stdout_lines[2]"

#    - debug:
#        var: cluster.stdout_lines[2]

# check nsx edge
- hosts: edge
  gather_facts: no
  tasks:
    - name: check manager connecting on edge
      raw: get managers
      register: edgemgr
      failed_when: "'Connected' not in edgemgr.stdout"

#    - debug:
#        var: edgemgr.stdout_lines

    - name: check controller connecting on edge 
      raw: get controllers
      register: edgectr
      failed_when: "'connected' not in edgectr.stdout"
#    - debug:
#        var: edgectr.stdout_lines


# check nsx hosts

- hosts: host
  gather_facts: no
  tasks:
    - name: check manager connection on hosts
      raw: nsxcli -c get managers
      register: mgrconn
      failed_when: "'Connected' not in mgrconn.stdout_lines[0]"
#    - debug:
#        var: mgrconn.stdout_lines

    - name: check controller connection on hosts
      raw: nsxcli -c get controllers
      register: ctrconn
      failed_when: "'connected' not in ctrconn.stdout"
#    - debug: 
#        var: ctrconn.stdout_lines[2]

- hosts: manager,controller,edge
  gather_facts: no
  any_errors_fatal: true
  vars_files:
    - ./var.yml
  tasks:
    - name: check ntp server configuration 
      raw: get ntp-server
      register: ntp
      failed_when: ntp.stdout_lines[0] is undefined or ntp.stdout_lines[0] !=  "{{ misc.ntp }}"
  
    - name: check log server configuration 
      raw: get logging-servers
      register: log
      failed_when: log.stdout_lines[0] is undefined or "{{ misc.log }}" not in log.stdout_lines[0]


- hosts: host
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: mtu ping 
      command: 'vmkping ++netstack=vxlan -d -s 1574 "{{ item }}"'
      with_items:
        - "{{groups['vtep']}}"
      register: ping
#      failed_when: ping.stdout is undefined
      tags:
        - ping

# for pks lab only, connfigure route to pks subnet 
#    - name: set static route to 192.168.64.0/18 
#      raw:  set route prefix 192.168.64.0/18 gateway 192.168.0.59 
